# Generated by Django 3.2.15 on 2022-10-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_enrollment_tool', '0005_remove_uuid_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfenrollmentcourse',
            name='course_instance_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='selfenrollmentcourse',
            name='role_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='selfenrollmentcourse',
            unique_together={('course_instance_id', 'role_id')},
        ),
    ]
