# Generated by Django 3.2.23 on 2024-06-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_enrollment_tool', '0007_update_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfenrollmentcourse',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selfenrollmentcourse',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
