# Generated by Django 3.2.23 on 2024-07-09 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_enrollment_tool', '0008_set_date_restrictions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='selfenrollmentcourse',
            unique_together={('course_instance_id', 'role_id', 'start_date', 'end_date')},
        ),
    ]
