# Generated by Django 3.2.23 on 2024-07-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_enrollment_tool', '0009_alter_unique_together_constraint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='selfenrollmentcourse',
            unique_together=set(),
        ),
    ]
