# Generated by Django 3.2.16 on 2023-02-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_account_admin_tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaltool',
            name='canvas_account_id',
            field=models.CharField(default='*', max_length=8),
        ),
        migrations.AlterField(
            model_name='externaltool',
            name='canvas_course_id',
            field=models.CharField(default='*', max_length=8),
        ),
        migrations.AlterField(
            model_name='externaltool',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='externaltool',
            name='name',
            field=models.CharField(choices=[('canvas_site_creator', 'Canvas Site Creator'), ('lti_tools_usage', 'LTI Tools Usage'), ('courses_in_this_account', 'Courses in this account')], max_length=32),
        ),
    ]
