# Generated by Django 3.2.18 on 2023-04-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_account_admin_tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasSchoolTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.IntegerField()),
                ('school_id', models.CharField(db_index=True, max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('include_course_info', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'canvas_school_template',
            },
        )
    ]
