# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-04 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bulk_course_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkCourseSettingsJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(max_length=10)),
                ('term_id', models.IntegerField(blank=True, null=True)),
                ('setting_to_be_modified', models.CharField(choices=[(b'is_public', b'Course is public'), (b'is_public_to_auth_users', b'Course is public to auth users'), (b'public_syllabus', b'Public syllabus'), (b'public_syllabus_to_auth', b'Syllabus is public to auth users')], default=b'is_public', max_length=20)),
                ('desired_setting', models.BooleanField(choices=[(True, b'True'), (False, b'False')], default=True)),
                ('workflow_status', models.CharField(choices=[(b'NEW', b'New'), (b'QUEUED', b'Queued'), (b'IN_PROGRESS', b'In progress'), (b'COMPLETED_SUCCESS', b'Completed Success'), (b'COMPLETED_ERRORS', b'Completed Errors'), (b'FAILED', b'Failed')], default=b'NEW', max_length=20)),
                ('related_job_id', models.IntegerField(null=True)),
                ('created_by', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bulk_course_settings_job',
            },
        ),
        migrations.CreateModel(
            name='BulkCourseSettingsJobDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_course_id', models.IntegerField(blank=True, null=True)),
                ('current_setting_value', models.CharField(blank=True, max_length=20, null=True)),
                ('prior_state', models.CharField(max_length=2000, null=True)),
                ('post_state', models.CharField(max_length=2000, null=True)),
                ('workflow_status', models.CharField(choices=[(b'NEW', b'New'), (b'SKIPPED', b'Skipped'), (b'COMPLETED', b'Completed'), (b'FAILED', b'Failed')], default=b'NEW', max_length=20)),
                ('is_modified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_job_process_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulk_course_settings.BulkCourseSettingsJob')),
            ],
            options={
                'db_table': 'bulk_course_settings_job_details',
            },
        ),
    ]
