# Generated by Django 3.2.16 on 2023-02-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_course_settings', '0004_auto_20180810_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='details',
            name='workflow_status',
            field=models.CharField(choices=[('NEW', 'New'), ('SKIPPED', 'Skipped'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='desired_setting',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='True', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='job',
            name='setting_to_be_modified',
            field=models.CharField(choices=[('is_public', 'Course is open to the public'), ('is_public_to_auth_users', 'Course is open to all authenticated users'), ('public_syllabus', 'Syllabus is open to the public'), ('public_syllabus_to_auth', 'Syllabus is open to all authenticated users')], default='is_public', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='workflow_status',
            field=models.CharField(choices=[('NEW', 'New'), ('QUEUED', 'Queued'), ('IN_PROGRESS', 'In progress'), ('COMPLETED_SUCCESS', 'Completed successfully'), ('COMPLETED_ERRORS', 'Completed with errors'), ('FAILED', 'Failed')], default='NEW', max_length=20),
        ),
    ]
