# Generated by Django 3.2.20 on 2024-01-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_course_settings', '0006_alter_job_meta_term_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='details_failed_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='details_skipped_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='details_success_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='details_total_count',
            field=models.IntegerField(null=True),
        ),
    ]
