# Generated by Django 3.2.19 on 2024-02-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_course_settings', '0008_remove_detail_counts_from_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='term_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
