# Generated by Django 3.2.20 on 2024-01-17 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(max_length=10)),
                ('term_id', models.CharField(blank=True, max_length=10, null=True)),
                ('workflow_status', models.CharField(choices=[('NEW', 'New'), ('QUEUED', 'Queued'), ('IN_PROGRESS', 'In progress'), ('COMPLETED_SUCCESS', 'Completed successfully'), ('COMPLETED_ERRORS', 'Completed with errors'), ('FAILED', 'Failed')], default='NEW', max_length=30)),
                ('created_by_user_id', models.CharField(max_length=15)),
                ('user_full_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bulk_publish_courses_job',
            },
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_course_id', models.PositiveIntegerField()),
                ('workflow_status', models.CharField(choices=[('NEW', 'New'), ('SKIPPED', 'Skipped'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_state', models.CharField(max_length=2000, null=True)),
                ('parent_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_details', to='publish_courses.job')),
            ],
            options={
                'db_table': 'bulk_publish_courses_job_details',
            },
        ),
    ]
