# Generated by Django 3.2.20 on 2024-01-09 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish_courses', '0002_auto_20240108_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job',
        ),
    ]
